export const mockProducts = [
    {
        id: "prod-1",
        name: "Classic Cotton T-Shirt",
        price: 29.99,
        originalPrice: 39.99,
        discount: 25,
        images: [
        "/images/cottonShirt1.png?height=400&width=400",
        "/images/cottonShirt2.png?height=400&width=400",
        "/images/cottonShirt3.png?height=400&width=400",
        "/images/cottonShirt4.png?height=400&width=400",
        ],
        rating: 4.5,
        reviewCount: 128,
        description: "A comfortable and versatile cotton t-shirt perfect for everyday wear.",
    },
    {
        id: "prod-2",
        name: "Premium Denim Jeans",
        price: 79.99,
        images: [
        "/images/Denim1.jpeg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.8,
        reviewCount: 94,
        description: "High-quality denim jeans with a modern fit and exceptional durability.",
    },
    {
        id: "prod-3",
        name: "Casual Hooded Sweatshirt",
        price: 49.99,
        originalPrice: 69.99,
        discount: 28,
        images: [
        "/images/Hoodie1.jpeg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.3,
        reviewCount: 76,
        description: "A cozy hooded sweatshirt perfect for casual outings or relaxing at home.",
    },
    {
        id: "prod-4",
        name: "Leather Crossbody Bag",
        price: 89.99,
        images: [
        "/images/CrossBag1.jpeg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.7,
        reviewCount: 52,
        description: "A stylish leather crossbody bag with multiple compartments for organization.",
    },
    {
        id: "prod-5",
        name: "Athletic Running Shoes",
        price: 119.99,
        images: [
        "/images/Shoes1.jpeg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.6,
        reviewCount: 108,
        description: "Lightweight and responsive running shoes designed for performance and comfort.",
    },
    {
        id: "prod-6",
        name: "Wireless Bluetooth Earbuds",
        price: 59.99,
        originalPrice: 79.99,
        discount: 25,
        images: [
        "/images/EarBuds1.jpeg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.2,
        reviewCount: 87,
        description: "High-quality wireless earbuds with exceptional sound and long battery life.",
    },
    {
        id: "prod-7",
        name: "Stainless Steel Water Bottle",
        price: 24.99,
        images: [
        "/images/bottle1.jpg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.9,
        reviewCount: 143,
        description: "A durable stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
    },
    {
        id: "prod-8",
        name: "Polarized Sunglasses",
        price: 39.99,
        originalPrice: 59.99,
        discount: 33,
        images: [
        "/images/glasses1.png?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        "/placeholder.svg?height=400&width=400",
        ],
        rating: 4.4,
        reviewCount: 65,
        description: "Stylish polarized sunglasses that provide 100% UV protection and reduce glare.",
    },
]
